### PR TITLE
55 need ability to add items to cart

### LINKED ISSUE #55: Need ability to add items to cart
Currently no way to actually add items to cart nor persist items in cart.

- [ ] Need ability to add items into cart from category page
- [ ] Add make a product description page and add items from product page (this is currently considered optional)
- [ ] Need data to persist for items in cart, should still be there even on page navigation

### PR DESCRIPTION
**Pull request by Kevin-Aguirre**
# New Feature 
Products in the category section now have a `Add to Cart` button which adds the product to the cart (if the product is already in the cart, the quantity is incremented by 1).

One change is that when a product in the cart has a quantity of 1 and is decremented, the item is removed from the cart.  

# Important Note
Items in the cart are being stored using `localStorage` since there is not an endpoint in the backend for cart items. When the endpoints are available functions that need to be changed to switch out of `localStorage` are all in `/utils/cartFunctions.js`.

### CODE REVIEW

**Comment by Connor-Skudlarek** [comment]
@Kevin-Aguirre Looks like there is a breaking change in /cart. I'll give it a quick look and see if I can fix before getting back to the admin dashboard.

If I can't, run the `npm run build` command to follow the stack trace to debug.

**Comment by Kevin-Aguirre** [comment]
@Connor-Skudlarek  I think I fixed the build error, it was an issue with localStorage being undefined because of server-side rendering.

**Comment by Connor-Skudlarek** [comment]
Confirmed the following:

- [x] Run build works
- [x] Adding to cart works
- [x] Multiple clicks from category increments cart
- [x] Qty 0 removes from cart
- [x] Nothing broken or missing in codebase changes

**Review by Connor-Skudlarek — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
